### ISSUE TITLE
Add tests for vector 

### ISSUE THREAD

**Issue by GlaceCoding** [mli42/containers_test#11]
Hi @mli42 ,

The subject of ft_containers said:
> Memory leakage occurs in C++ too. When you allocate memory, you must avoid memory leaks

But there is no test to check if the value is correctly destroy before deallocate the memory. Can I make a test to check if the good number of deconstructor are called ?

**Comment by mli42** [comment]
Hi @GlaceCoding,

I'm afraid the number of call to destructor is implementation-dependent.
An easy way to code this test, is to print something during the destructor of a custom class, the output comparaison will check if the same amount of destructor were called. But I think this test is too harsh and might depend on the host machine ...

For leaks, you might want to run the tests with fsanitize flag !

**Comment by GlaceCoding** [comment]
With a class wrapper we can count how many constructor and deconstructor are called, and just verify the number of call match together, if we check outside the scope, the number of cons/decons should be the same

**Comment by mli42** [comment]
You want to compare the number of constructors and destructor of the same class ? Without comparing to the real container ?
Also calling the destructor does not guarantee deallocating all the allocated memory

**Comment by mli42** [comment]
Ok I think I got what you are thinking, instead of a class wrapper, you can also make a static property.
But still, it does not prevent other memory leaks, to me, fsanitize is the best solution

**Comment by GlaceCoding** [comment]
I tried something it was not very relevant, It need to much work to do and it is not sure that will be not make some false positive.
